### ISSUE TITLE
canvas2d not supported on browser - use pixi.js-legacy

### ISSUE THREAD

**Issue by jpalala** [alephjs/alephjs.org#16]
See screenshot below:

<a href="https://ibb.co/Scj7CfD"><img src="https://i.ibb.co/m0jFWNr/https-alephjs-org.png" alt="https-alephjs-org" border="0"></a>

I've tried also enabling anything I found on WebGL, through by going to `chrome://flags` .

**Comment by jpalala** [comment]
I'm on chrome btw - v 83.0.4103.97 (Official Build) (64-bit)

**Comment by ije** [comment]
now it should work, can you please try again? thanks!
https://alephjs.org

**Comment by jpalala** [comment]
It works! @ije 👍 🎉 thanks! 

This issue can now be closed.
