### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by shadowtime2000** [alephjs/alephjs.org#22]
We have a search bar, but all it does is tell the user that search is not currently implemented. This basically a tracking issue to implement it. The code for it is [here](https://github.com/alephjs/alephjs.org/blob/5987baa5192a311642ba05456db1f53e0028b8bc/pages/docs.tsx#L162).

**Comment by ije** [comment]
i am going to close this, since the new docs page has a simple search function now, will improve this in the future if necessary.
