### ISSUE TITLE
Update documentation about markdown pages

### ISSUE THREAD

**Issue by Insert-Creative-Name-Here** [alephjs/alephjs.org#42]
The documentation says that Aleph.js supports pages that have markdown natively. However, as of v0.3 (see: [issue #131 on aleph.js](https://github.com/alephjs/aleph.js/issues/131)), builtin markdown page routing was removed.

There's no documentation about how to use plugins either.

As of now, if someone wants to find out how to use markdown pages, they'd have to dig through the example code. But that takes waaay too long.

**Comment by ije** [comment]
I'm updating the doc, still have some works need to finished...but you can check the undeployed docs about using pugins:
https://github.com/alephjs/alephjs.org/blob/feat-update-to-0.3/pages/docs/advanced-features/using-plugins.md

**Comment by Insert-Creative-Name-Here** [comment]
Oh, thanks! This solves my issue.
I didn't know there were undeployed docs
